#_______________________________________________________________________________
# processing and analysing raw count matrices
#_______________________________________________________________________________

#--------------------- settings ------------------------------------------------
  
# Needed packages: Seurat package, harmony package, SingleCellExperiment, scDblFinder,
# stats, monocle3 (https://cole-trapnell-lab.github.io/monocle3/docs/installation/)

# setwd('C:/Users/groen/OneDrive/SCD/scd-projects/MER-PC-4')
dir.create('output/all/',recursive=T, showWarnings = FALSE)


#--------------------- load count matrices -------------------------------------
# import cellranger outputs to seurat objects for each library

data.list <- list()
fileNames <- list.files('./data',pattern="filtered")

for (j in 1:length(fileNames)){
 data <- Seurat::Read10X(data.dir = paste0('./data/',fileNames[j]),strip.suffix = T)
 data.list[[sub("^([^-]*).*","\\1", fileNames[j])]] <- data
 rm(data)
 data.list[[j]] <-  Seurat::CreateSeuratObject(data.list[[j]])
 data.list[[j]] <-  Seurat::PercentageFeatureSet(data.list[[j]], pattern = "^Mt-|^mt-|^MT-", col.name = "percent.mt")
 data.list[[j]] <-  Seurat::PercentageFeatureSet(data.list[[j]], pattern = "^RP[SL]",col.name = "percent.ribo")
}

names(data.list); rm(fileNames)
 

#--------------------- qc and filter--------------------------------------------
# filter each library separately with variable cutoffs
 
max_mito <- 10
max_transcripts <- 50000
filter_criteria <- data.frame(row.names = c('g011','g012','g013','g014','g016','g017','g018','g019','g020'),
                             transcripts = c(500, 3000, 500, 1313, 4000, 4000, 4000, 4000, 4000))
  
filtering <- function(x){
lapply(seq_along(x), function(i) {
  lib_name <- names(x[i])
  stopifnot(length(lib_name == 1) & lib_name %in% rownames(filter_criteria))
  filter_tmp <- filter_criteria[lib_name,,drop=F]
  x[[i]] <- subset(x = x[[i]], subset = nCount_RNA > filter_tmp$transcripts & nCount_RNA < max_transcripts & percent.mt < max_mito)
  })
 }
libnames <- names(data.list)
data.list <- filtering(data.list)
names(data.list) <- libnames
rm(filter_criteria); rm(max_mito); rm(max_transcripts); rm(libnames)


#--------------------- merge libraries  ----------------------------------------

cell.ids <- names(data.list)
scd <- merge(data.list[[1]], data.list[c(-1)], add.cell.ids=cell.ids)
scd$Library <- sub("\\_.*","", rownames(scd[[]]))
rm(cell.ids); rm(data.list)


#--------------------- add metadata --------------------------------------------
# add donor information to each demultiplexed library

# import demultiplexing results generated by the soupourcell script (clusters.tsv)
dir_demux <- './data/souporcell_output/' # path to souporcelloutput, output files saved per folder named after each library.

meta_files <- list.dirs(dir_demux,full.names=T)
meta_files <- meta_files[grep("g011|g012|g013|g014",meta_files)] # select only the multiplexed libraries (first 4)
names(meta_files)<-gsub(".*/","",meta_files)
meta_files<- lapply(seq_along(meta_files), function(i) {
  out <- read.delim(paste0(meta_files[[i]],"/clusters.tsv"),row.names=1)
  rownames(out) <- paste0(names(meta_files[i]),"_",rownames(out))
  out$sample <- out$status
  out$sample <- ifelse(out$status == "singlet", paste0(names(meta_files[i]),"_",out$assignment), out$status)
  return(out)    
})
meta_demux <- data.frame(do.call(rbind,meta_files))
rownames(meta_demux) <- gsub("-1","", rownames(meta_demux))
scd$demux_sample <- meta_demux[rownames(scd[[]]),"sample"]
scd$demux_sample <- ifelse(is.na(scd$demux_sample),scd$Library, scd$demux_sample)
rm(meta_demux); rm(meta_files); rm(dir_demux); 


# import and add metadata (Library_metadata.txt)
meta_library <- read.delim('./docs/Library_metadata.txt', row.names = 1)
scd@meta.data <- cbind(scd[[]], meta_library[match(scd$demux_sample,rownames(meta_library)),])
scd$Donor[is.na(scd$Donor)] <- 'NA'
rm(meta_library)


#--------------------- normalize and process  ----------------------------------

PCchoice <- 22 # for whole dataset

scd <- Seurat::NormalizeData(scd, assay = "RNA", normalization.method = "LogNormalize", 
                             scale.factor = 10000)
scd <- Seurat::FindVariableFeatures(scd,selection.method = "vst", nfeatures = 2000)
scd <- Seurat::ScaleData(scd)
scd <- Seurat::RunPCA(scd, features = Seurat::VariableFeatures(object = scd))
# scd <- Seurat::RunUMAP(scd, dims = 1:PCchoice)
scd <- harmony::RunHarmony (scd, group.by.vars = c('Library','Donor'), 
                            plot_convergence = TRUE,
                            dims.use = 1:PCchoice)
scd <- Seurat::RunUMAP(scd, reduction="harmony",dims = 1:PCchoice, verbose = F)

umap <- Seurat::DimPlot(scd, group.by = 'Library')
pdf('output/all/umap.pdf',width = 7,height = 8);print(umap);dev.off()


#--------------------- clustering analysis  ------------------------------------
# identify clusters in the dataset

k.param = 100
resolution = 0.2
algorithm = 1

scd <- Seurat::FindNeighbors(scd, reduction = "harmony", dims = 1:PCchoice,k.param=k.param)
scd <- Seurat::FindClusters(scd,algorithm=algorithm, resolution = resolution)   

clusters.umap <- Seurat::DimPlot(scd, reduction="umap", group.by = "seurat_clusters",repel=T)
pdf('output/all/umap_clusters.pdf',width = 7,height = 8);print(clusters.umap);dev.off()


# identify markers per cluster
library(limma)
markers <- Seurat::FindAllMarkers(scd,assay = "RNA", slot="data", only.pos = TRUE, min.pct = 0.33, 
                                  max.cells.per.ident = Inf, logfc.threshold = -Inf, test="wilcox", return.thresh = 0.01)

saveRDS(markers, file='output/all/DE_markers.rds')


#--------------------- identify putative doublets  -----------------------------
# use scDblFinder to infer in silico doublets and add to metadata

sce <- Seurat::as.SingleCellExperiment(scd)
sce <- scDblFinder::scDblFinder(sce,samples = "Library",clusters = "seurat_clusters")
doublets <- sce@colData[,c("scDblFinder.class","scDblFinder.score")]

scd@meta.data <- cbind(scd@meta.data,doublets[rownames(scd@meta.data),])
rm(sce)


#--------------------- save object ---------------------------------------------

saveRDS(scd, file='seurat_all.rds')

